# Generated by Django 4.2.1 on 2023-07-31 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('access_office', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pedestrian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AlterField(
            model_name='document',
            name='auto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='access_office.automobile', verbose_name='Автомобиль'),
        ),
        migrations.AlterField(
            model_name='driver',
            name='full_name',
            field=models.CharField(db_index=True, max_length=1000),
        ),
        migrations.AddField(
            model_name='document',
            name='pedestrian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='access_office.pedestrian', verbose_name='Пешеход'),
        ),
    ]
